name: RDP-Windows-HD
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download & Install CRD
      run: |
        $URL = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
        Invoke-WebRequest -Uri $URL -OutFile "crd.msi"
        Start-Process msiexec.exe -Wait -ArgumentList "/i crd.msi /qn"
    - name: Masukkan Kode Otorisasi
      run: |
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AfrIepDkyQ8KyehyKlezYJQnUepa50STr51hijljDlqHS0cyjBolaF1GmJZOsISzKO7-ZA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=123456
        
