name: RDP-ULTIMATE-FINAL
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Mengunduh Chrome Remote Desktop
      run: |
        $URL = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
        Invoke-WebRequest -Uri $URL -OutFile "crd.msi"
        Start-Process msiexec.exe -Wait -ArgumentList "/i crd.msi /qn"
      #

    - name: Menjalankan Host RDP
      run: |
        # GANTI TULISAN DI BAWAH INI DENGAN KODE POWERSHELL DARI GOOGLE:
        & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AfrIepBRTDx-av2BruIoyH71g9J77yRtBtAseu0CEmlc4-RknvNC3CZSsp9h7SWixODgNg" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=123456
      #

    - name: Menjaga Server Tetap Hidup
      run: |
        $n = 360
        do {
            Write-Host "Server Aktif... Sisa waktu: $n menit"
            Start-Sleep -Seconds 60
            $n--
        } while ($n -gt 0)
      #
      
